###### 1. Import numpy as np and see the version

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

###### 2. How to create a 1D array? 
Create a 1D array of numbers from 0 to 9

In [3]:
ar=np.arange(10)

In [4]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 3. How to create a boolean array?
Create a 3×3 numpy array of all True’s

In [7]:
ar1= np.ones((3,3),dtype=bool)

In [8]:
ar1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

###### 4.Extract all odd numbers from arr

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar= arr[1:10:2]
ar

array([1, 3, 5, 7, 9])

In [11]:
arr[arr % 2 == 1]
#> array([1, 3, 5, 7, 9]) 

array([1, 3, 5, 7, 9])

###### 5.Replace all odd numbers in arr with -1

In [14]:
arr[1:10:2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
arr[arr % 2 == 1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###### 6.Replace all odd numbers in arr with -1 without changing arr

In [17]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### 7.Convert a 1D array to a 2D array with 2 rows

In [20]:
arr=np.arange(10)

In [23]:
arr.reshape(2,-1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])